repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        exclude: "(^|/)alembic(/|$)"
      - id: end-of-file-fixer
        exclude: "(^|/)alembic(/|$)"
  - repo: local
    hooks:
      - id: pycln
        name: pycln
        stages: [commit]
        types: [python]
        language: system
        args: ["--all"]
        entry: pycln
        exclude: "(^|/)alembic(/|$)"
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        types: [python]
        language: system
        entry: black
        exclude: "(^|/)alembic(/|$)"
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        types: [python]
        language: system
        args: ["--profile", "black", "--filter-files"]
        entry: isort
        exclude: "(^|/)alembic(/|$)"
