services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: aquarium_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aquarium_network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: aquarium_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aquarium_network
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning

volumes:
  postgres_data:
  redis_data:

networks:
  aquarium_network:
    driver: bridge
